version: '3.7'
services:
  redis:
    image: redis:5.0.3
    container_name: redis
    volumes:
      - type: volume
        source: redis
        target: /data
    ports:
      - "6379:6379"

volumes:
  redis: